language: android
android:
  components:
    - build-tools-22.0.1
    - android-23
    - extra-android-m2repository
    - extra-android-support
script:
  - sudo ./gradlew assembleRelease
deploy:
  provider: releases
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
