language: android
android:
  components:
    - build-tools-22.0.1
    - android-23
    - extra-android-m2repository
    - extra-android-support
script:
  - curl https://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip -O > /dev/null
  - unzip android-ndk-r14b-linux-x86_64.zip > /dev/null
  - yes | ~/android/sdk/tools/bin/sdkmanager 'ndk-bundle'
  - echo y | sdkmanager 'ndk-bundle'
  - chmod +x ./gradlew
  - ./gradlew assembleRelease
deploy:
  provider: releases
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
